// Mocks generated by Mockito 5.4.6 from annotations
// in sitecat/test/providers/monitoring_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sitecat/models/monitoring_result.dart' as _i2;
import 'package:sitecat/models/site.dart' as _i5;
import 'package:sitecat/services/monitoring_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMonitoringResult_0 extends _i1.SmartFake
    implements _i2.MonitoringResult {
  _FakeMonitoringResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MonitoringService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMonitoringService extends _i1.Mock implements _i3.MonitoringService {
  MockMonitoringService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setHistoryLimit(bool? isPremium) => super.noSuchMethod(
    Invocation.method(#setHistoryLimit, [isPremium]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.MonitoringResult> checkSite(_i5.Site? site) =>
      (super.noSuchMethod(
            Invocation.method(#checkSite, [site]),
            returnValue: _i4.Future<_i2.MonitoringResult>.value(
              _FakeMonitoringResult_0(
                this,
                Invocation.method(#checkSite, [site]),
              ),
            ),
          )
          as _i4.Future<_i2.MonitoringResult>);

  @override
  _i4.Stream<List<_i2.MonitoringResult>> getSiteResults(
    String? siteId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSiteResults, [siteId], {#limit: limit}),
            returnValue: _i4.Stream<List<_i2.MonitoringResult>>.empty(),
          )
          as _i4.Stream<List<_i2.MonitoringResult>>);

  @override
  _i4.Future<_i2.MonitoringResult?> getLatestResult(String? siteId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestResult, [siteId]),
            returnValue: _i4.Future<_i2.MonitoringResult?>.value(),
          )
          as _i4.Future<_i2.MonitoringResult?>);

  @override
  _i4.Future<void> deleteSiteResults(String? siteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSiteResults, [siteId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMonitoringResult(String? siteId, String? resultId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMonitoringResult, [siteId, resultId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
