// Mocks generated by Mockito 5.4.6 from annotations
// in sitecat/test/providers/site_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:sitecat/models/site.dart' as _i4;
import 'package:sitecat/services/site_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SiteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSiteService extends _i1.Mock implements _i2.SiteService {
  MockSiteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> createSite(_i4.Site? site) =>
      (super.noSuchMethod(
            Invocation.method(#createSite, [site]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createSite, [site]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Stream<List<_i4.Site>> getUserSites() =>
      (super.noSuchMethod(
            Invocation.method(#getUserSites, []),
            returnValue: _i3.Stream<List<_i4.Site>>.empty(),
          )
          as _i3.Stream<List<_i4.Site>>);

  @override
  _i3.Future<_i4.Site?> getSite(String? siteId) =>
      (super.noSuchMethod(
            Invocation.method(#getSite, [siteId]),
            returnValue: _i3.Future<_i4.Site?>.value(),
          )
          as _i3.Future<_i4.Site?>);

  @override
  _i3.Future<void> updateSite(_i4.Site? site) =>
      (super.noSuchMethod(
            Invocation.method(#updateSite, [site]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSite(String? siteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSite, [siteId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleMonitoring(String? siteId, bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#toggleMonitoring, [siteId, enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateLastChecked(String? siteId, DateTime? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastChecked, [siteId, timestamp]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.Site>> getMonitoringSites() =>
      (super.noSuchMethod(
            Invocation.method(#getMonitoringSites, []),
            returnValue: _i3.Stream<List<_i4.Site>>.empty(),
          )
          as _i3.Stream<List<_i4.Site>>);

  @override
  _i3.Future<bool> urlExists(String? url, {String? excludeSiteId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #urlExists,
              [url],
              {#excludeSiteId: excludeSiteId},
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> validateUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#validateUrl, [url]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> getSiteCount() =>
      (super.noSuchMethod(
            Invocation.method(#getSiteCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Stream<List<_i4.Site>> searchSites(String? searchTerm) =>
      (super.noSuchMethod(
            Invocation.method(#searchSites, [searchTerm]),
            returnValue: _i3.Stream<List<_i4.Site>>.empty(),
          )
          as _i3.Stream<List<_i4.Site>>);
}
