// Mocks generated by Mockito 5.4.6 from annotations
// in sitecat/test/providers/subscription_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:in_app_purchase/in_app_purchase.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:sitecat/services/subscription_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SubscriptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionService extends _i1.Mock
    implements _i2.SubscriptionService {
  MockSubscriptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> hasLifetimeAccess() =>
      (super.noSuchMethod(
            Invocation.method(#hasLifetimeAccess, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> purchaseLifetimeAccess() =>
      (super.noSuchMethod(
            Invocation.method(#purchaseLifetimeAccess, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> restorePurchases() =>
      (super.noSuchMethod(
            Invocation.method(#restorePurchases, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.ProductDetails?> getProductDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getProductDetails, []),
            returnValue: _i3.Future<_i4.ProductDetails?>.value(),
          )
          as _i3.Future<_i4.ProductDetails?>);
}

/// A class which mocks [ProductDetails].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductDetailsCustom extends _i1.Mock implements _i4.ProductDetails {
  MockProductDetailsCustom() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i5.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
          )
          as String);

  @override
  String get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
          )
          as String);

  @override
  String get price =>
      (super.noSuchMethod(
            Invocation.getter(#price),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#price),
            ),
          )
          as String);

  @override
  double get rawPrice =>
      (super.noSuchMethod(Invocation.getter(#rawPrice), returnValue: 0.0)
          as double);

  @override
  String get currencyCode =>
      (super.noSuchMethod(
            Invocation.getter(#currencyCode),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#currencyCode),
            ),
          )
          as String);

  @override
  String get currencySymbol =>
      (super.noSuchMethod(
            Invocation.getter(#currencySymbol),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#currencySymbol),
            ),
          )
          as String);
}
