// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQXRdyBYssNHByBY4WowJCoebWNN4T3Gc',
    appId: '1:974974534435:android:168c3317e726acfecdc296',
    messagingSenderId: '974974534435',
    projectId: 'sitecat-dev',
    storageBucket: 'sitecat-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArhmTnny6rdeCtikweuX6DrG6H-4wzDdk',
    appId: '1:974974534435:ios:cef0f75a7150e07bcdc296',
    messagingSenderId: '974974534435',
    projectId: 'sitecat-dev',
    storageBucket: 'sitecat-dev.firebasestorage.app',
    androidClientId:
        '974974534435-g6naqfrrc6d18h48kgrfgh200ov1mcs1.apps.googleusercontent.com',
    iosClientId:
        '974974534435-acs3q36ciqdm67u3ba5ea2ruk2ov9mo3.apps.googleusercontent.com',
    iosBundleId: 'jp.netplan.sitecat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr4940Dyo0wHnoQGFHiAaNrr95BrX_oW4',
    appId: '1:974974534435:web:41bf43903bb5f496cdc296',
    messagingSenderId: '974974534435',
    projectId: 'sitecat-dev',
    authDomain: 'sitecat-dev.firebaseapp.com',
    storageBucket: 'sitecat-dev.firebasestorage.app',
    measurementId: 'G-WNDH3NVRTE',
  );
}
